name: Metrics
on:
  schedule:
    - cron: "0 0 * * SUN"
  workflow_dispatch:
  push: { branches: "main" }
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@v3.34
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: dev01d
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: America/Los_Angeles
          # Plugins
          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: B
          plugin_languages: yes
          plugin_languages_ignored: jinja, swift, mdx, ruby
      
