# Visit https://github.com/lowlighter/metrics/blob/master/action.yml for full reference
name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{ cron: "0 * * * *" }]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: { branches: "main" }
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: dev01d
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: America/Los_Angeles

          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: B

          plugin_languages: yes
          plugin_languages_ignored: jinja, swift, Makefile, ruby, Vim Script, css
          plugin_languages_details: percentage
          plugin_languages_limit: 8
          plugin_languages_sections: most-used
